management:
  endpoints:
    web:
      exposure:
          include: "info,health,metrics"

server:
  port: 8080
spring:
  application:
    name: "takehome"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-ousg77uz1ajb0gz0.us.auth0.com/

auth0:
  audience: https://takehome.yfs/api/

logging:
  level:
    root: INFO

rate:
  limit:
    unauthenticated: 5
    authenticated: 10




