management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
          include: "*"

server:
  port: 8090
spring:
  application:
    name: "takehome"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-ousg77uz1ajb0gz0.us.auth0.com/

auth0:
  audience: https://takehome.yfs/api/

logging:
  level:
    root: INFO

rate:
  limit:
    unauthenticated: 5
    authenticated: 10




